### ISSUE TITLE
关于跟tabbarios合并使用出现的一个问题

### ISSUE THREAD

**Issue by hainuo** [starlight36/react-native-navigator-router#1]
http://v.youku.com/v_show/id_XMTYwNTQ3NDMyMA==.html

视频已经上传至优酷了 你可以点击查看 
主要就是  点击的时候有很多时候要点击两下才会有路由
https://github.com/hainuo/reactnativeapp   这个是版本库
有空的话麻烦你给看看用法上哪里不太争取

**Comment by starlight36** [comment]
我看了你录制的视频，下面两点可能对你会有帮助：

1. 尽量让TabbarIOS组件的生命周期和Navigator不要有交叉。因为Navigator会保留栈内的每个页，而不是切页了销毁先前的。生命周期交叉之后可能会有一些奇怪的问题。
2. App通常的一个实践是，栈底页面带Tabbar，但是打开到栈内的页面，不带Tabbar。这样App一致性更好一些，同时也规避了1提到的这个问题。

**Comment by starlight36** [comment]
@hainuo 你好！我看了你录制的视频，希望下面两点能对你会有帮助：
1. 尽量让TabbarIOS组件的生命周期和Navigator不要有交叉。因为Navigator会保留栈内的每个页，而不是切页了销毁先前的。生命周期交叉之后可能会有一些奇怪的问题。
2. App通常的一个实践是，栈底页面带Tabbar，但是打开到栈内的页面，不带Tabbar。这样App一致性更好一些，同时也规避了1提到的这个问题。

**Comment by hainuo** [comment]
看了你的回复 感觉自己应该是将这两个给混淆了    我应该在外层使用tabbarios  然后在  tabbarios的view中使用navigator-router  

  我是否可以按照web的思路来理解：   tabbarios  是一个多页面应用 mutable page app 的    而navigator-router 是一个 单页面的应用 single page app

  我现在的行为相当于在单页面里面嵌套多页面的东西导致 navigator-router 初始化失败问题  才导致这样的    所以点击出现两次并不是因为用法不对而是因为点击第一次后router 没有任何内容  再次点击 router才被初始化 才找到之前设置的根才找到其他的路由设置

你看我的理解是不是正确 
------------------ 原始邮件 ------------------
发件人: "Max Liu"notifications@github.com
发送时间: 2016年6月12日(星期天) 下午4:56
收件人: "starlight36/react-native-navigator-router"react-native-navigator-router@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Mention"mention@noreply.github.com;
主题: Re: [starlight36/react-native-navigator-router] 关于跟tabbarios合并使用出现的一个问题 (#1)

@hainuo 你好！我看了你录制的视频，希望下面两点能对你会有帮助：

尽量让TabbarIOS组&#x4EF6;的生命周期和Navigator不要有交叉。因为Navigator会保留栈内的每个页，而不是切页了销毁先前的。生命周期交叉之后可能会有一些奇怪的问题。

App通常的一个实践是，栈底页面带Tabbar，但是打开到栈内的页面，不带Tabbar。这样App一致性更好一些，同时也规避了1提到的这个问题。

&mdash;

**Comment by starlight36** [comment]
@hainuo 这样使用是可以的，不过我的本意是让router作为页面的根生命周期组件，让tabbar作为router中栈底页面的组件，tabbar的切换不经router管理，像原来一样使用state来控制切换。这样应该能更清晰一点。

**Comment by yedaodao** [comment]
@hainuo 你好，请问你的代码库中的代码和视频中演示的为同一份吗，因为我看到你的首页在`<IndexRoute component={App} />`中设置为底部的tabbar，这样在路由为'/'时，首页为底部导航组件。建议底部导航组件与container中的index合并为一个container

**Comment by hainuo** [comment]
是同一份的    我稍后处理下   多谢你的指导 
------------------ 原始邮件 ------------------
发件人: "daodao"notifications@github.com
发送时间: 2016年6月12日(星期天) 下午5:55
收件人: "starlight36/react-native-navigator-router"react-native-navigator-router@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Mention"mention@noreply.github.com;
主题: Re: [starlight36/react-native-navigator-router] 关于跟tabbarios合并使用出现的一个问题 (#1)

@hainuo 你好，请问你的代码库中的代码和视频中演示的为同一份吗，因为我看到你的首页在<IndexRoute component={App} />中设置为底部的tabbar，这样在路由为'/'时，首页为底部导航组&#x4EF6;。建议底部导航组&#x4EF6;与container中的index合并为一个container

&mdash;

**Comment by yedaodao** [comment]
@hainuo HI，如果是这个问题，麻烦搞定后回复下，方便close，非常感谢~

**Comment by hainuo** [comment]
@yedaodao  好的 今天没改成功 我明天再改改看  应该是因为我有些地方不熟悉的缘故。

**Comment by starlight36** [comment]
@hainuo 你是对的，这的确是个Bug。今天把ReactNative升级到了0.26之后，在原版Example里面重现了这个问题，已经找到解决方案了，我尽快提交。

**Comment by starlight36** [comment]
@hainuo Bug已解决，新版本是0.2.0，你可以升级一下试试看。

**Comment by hainuo** [comment]
好的 
------------------ 原始邮件 ------------------
发件人: "Max Liu"notifications@github.com
发送时间: 2016年6月13日(星期一) 晚上6:57
收件人: "starlight36/react-native-navigator-router"react-native-navigator-router@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Mention"mention@noreply.github.com;
主题: Re: [starlight36/react-native-navigator-router] 关于跟tabbarios合并使用出现的一个问题 (#1)

@hainuo Bug已解决，新版本是0.2.0，你可以升级一下试试看。

&mdash;

**Comment by hainuo** [comment]
测试可用   多谢 @starlight36

**Comment by hainuo** [comment]
http://v.youku.com/v_show/id_XMTYwNjk1NjQ3Mg==.html   修正后的视频如下  源代码也已经更新

**Comment by starlight36** [comment]
@hainuo 好的~
