### ISSUE TITLE
new bug in my project

### ISSUE THREAD

**Issue by hainuo** [starlight36/react-native-navigator-router#2]
[youtube地址](https://www.youtube.com/watch?v=J8vAT84-etw)    优酷上传转码失败  就上传到youtube了
稍后我重复上传成功了，就贴出优酷的视频地址来。

问题在视频的48s左右   右上角的icon.button的onpress 使用了
代码在 [header.js](https://github.com/pingang360/pgwapp/blob/master/src/components/header.js)

那个不断的闪屏 应该算是一个bug

**Comment by starlight36** [comment]
@hainuo 好的，我看一下

**Comment by hainuo** [comment]
@starlight36    如果可能的话还是拉取版本库  在视频中闪屏不是那么明显

**Comment by starlight36** [comment]
@hainuo 试验了一下，的确有闪烁的问题，不过可能需要在你的项目里面进行优化。首先是，在RN里面的React Router导航和在浏览器里面还是有点区别的。在二级页面跳回首页时候，应该使用back而不是直接push首页进去。直接push进去一个页面，相当于页面栈里面有两个首页。其次是ListView需要小心优化，处理好生命周期，尤其是切页动画时候。

**Comment by hainuo** [comment]
好的，多谢 指教，晚上我试试。  我了解的比较多，真正动手比较少，还需要补好多课啊。请见谅
------------------ 原始邮件 ------------------
发件人: "Max Liu"notifications@github.com
发送时间: 2016年6月18日(星期六) 下午3:20
收件人: "starlight36/react-native-navigator-router"react-native-navigator-router@noreply.github.com;
抄送: "hainuo"admin@hainuo.info;"Mention"mention@noreply.github.com;
主题: Re: [starlight36/react-native-navigator-router] new bug in my project(#2)

@hainuo 试验了一下，的确有闪烁的问题，不过可能需要在你的项目里面进行优化。首先是，在RN里面的React Router导航和在浏览器里面还是有点区别的。在&#x4E8C;级页面跳回首页时候，应该使用back而不是直接push首页进去。直接push进去一个页面，相当于页面栈里面有两个首页。其次是ListView需要小心优化，处理好生命周期，尤其是切页动画时候。

&mdash;
