### ISSUE TITLE
can we customize the effect when page pass to another page , currently it is just like "swipe" effect

### ISSUE THREAD

**Issue by panzt** [starlight36/react-native-navigator-router#3]

**Comment by starlight36** [comment]
Of course, you can simply pass a query string parameter `anim` to define which change effect to use. Something like this:

``` js
push('/about?anim=floatFromLeft')
```

We have already supported `floatFromLeft`, `floatFromLeft`, `pushFromRight` page change effects. But it will use fallback on Android platform.

**Comment by panzt** [comment]
it works. thanks
