### ISSUE TITLE
如何在跳转时传递参数呢？

### ISSUE THREAD

**Issue by shapenlone** [starlight36/react-native-navigator-router#5]
如何在跳转时传递参数呢？router.push('/test',param)????
谢谢

**Comment by starlight36** [comment]
第一种方式：

``` js
router.push('/test?key1=value1')
```

第二种方式：

``` js
router.push({
  pathname: '/users/12',
  query: { modal: true },
})
```

具体请参考React Router的文档：
 [https://github.com/reactjs/react-router/blob/master/docs/API.md#contextrouter](https://github.com/reactjs/react-router/blob/master/docs/API.md#contextrouter)

**Comment by shapenlone** [comment]
谢谢
