### ISSUE TITLE
关于 propetypes 的问题

### ISSUE THREAD

**Issue by hainuo** [starlight36/react-native-navigator-router#6]
![wechat20160812_1](https://cloud.githubusercontent.com/assets/421861/17640579/3c1dbeb4-6135-11e6-9ec8-c4f31d702ba1.png)

查来查去发现出错代码如下

```
    static contextTypes = {
        router: React.PropTypes.object.isRequired
    };
```

不知道怎么处理  当前版本应该能用但是如果要升级的话 肯定会有些问题了

**Comment by starlight36** [comment]
我关注一下这个问题~

**Comment by hainuo** [comment]
@starlight36  我删除了 node_modules 然后重新安装使用 react-native udpate 更新了版本本地构建信息，   react-native 使用0.30.0  react 使用15.2.0 发现问题没有了，我想可能是因为15.0.2 版本有特殊标记？ 

不好意思，给你带了了麻烦

**Comment by starlight36** [comment]
@hainuo 好的，有问题欢迎反馈~

**Comment by T12138** [comment]
import PropTypes from 'prop-types';不知道和这个有没有关？麻烦问下
